export const cloudComputeRegularPerformance = [
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
];

export const cloudComputeHighPerformanceAMD = [
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
];

export const cloudComputeHighPerformanceIntel = [
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
];

export const cloudComputeHighFrequency = [
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
  {
    vCPUs: "1 vCPU",
    Memory: "0.5 GB",
    Bandwidth: "0.50 TB",
    Storage: "10 GB",
    MonthlyPrice: "$2.5/mo",
    HourlyPrice: "$0.004/hr",
  },
];
